version: '3.1'

services:
  dbmysql:
    build: ./db
    ports:
      - "33000:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Irbhvfywtd@root0000
      # at first time, it is possible, you may need to run:
      #MYSQL_DATABASE=test1

    volumes:
      - ${DB_PATH_HOST}:${DB_PATH_CONTAINER}:rw

    container_name: dbincontainer


  adminer:
    build: ./adminer
    depends_on:
      - dbmysql
    links:
      - "dbmysql:db"
    ports:
      - "8080:8080"
    restart: always


  flaskapp:
    build: ./
    depends_on:
      - dbmysql
    volumes:
      - ${APP_REQUIREMENTS_HOST}:${APP_REQUIREMENTS_CONTAINER}:ro
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    container_name: flaskcontainer
    links:
    - "dbmysql:db"
    ports:
      - 80:5000
    working_dir: ${APP_PATH_CONTAINER}
    restart: always




